[CmdletBinding()]
param(
    [Parameter(Mandatory=$true)][ValidatePattern('^dev5054-[0-9]{8}T[0-9]{6}Z-[0-9a-f]{12}$')][string]$ReleaseId,
    [string]$OutputRoot='C:\DLE-OS\Qualification\DevResilience\Phase2',
    [string]$Phase1BaselineRoot='C:\DLE-OS\Qualification\DevResilience\Phase1\phase1-20260826T044745Z'
)

Set-StrictMode -Version Latest
$ErrorActionPreference='Stop'
$identity=[Security.Principal.WindowsIdentity]::GetCurrent();$principal=New-Object Security.Principal.WindowsPrincipal($identity)
if(-not$principal.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)-or-not[string]::Equals($identity.Name,'DLE-OS-HOST\Miguel',[StringComparison]::OrdinalIgnoreCase)){throw 'Phase 2 final regression requires elevated DLE-OS-HOST\Miguel.'}
$stamp=[DateTimeOffset]::UtcNow.ToString('yyyyMMddTHHmmssZ');$runRoot=Join-Path $OutputRoot ('phase2-final-regression-'+$stamp);$null=New-Item -ItemType Directory -Path $runRoot -Force
$release="C:\DLE-OS\Development\OperationalControlHost5054\Releases\$ReleaseId";$manifestPath="C:\DLE-OS\Development\OperationalControlHost5054\Manifests\$ReleaseId.json";$runtimeIdentity='DLE-OS-HOST\DLE-OS-DEV-CONTROL'

function Probe([string]$Uri,[switch]$DefaultCredentials){try{$p=@{Uri=$Uri;UseBasicParsing=$true;TimeoutSec=20};if($DefaultCredentials){$p.UseDefaultCredentials=$true};$r=Invoke-WebRequest @p;[ordered]@{Passed=([int]$r.StatusCode-eq200);Status=[int]$r.StatusCode;Body=$r.Content}}catch{[ordered]@{Passed=$false;Error=$_.Exception.Message}}}
function Sql([string]$Query){$c=New-Object Data.SqlClient.SqlConnection('Server=lpc:.\SQLEXPRESS;Database=master;Integrated Security=True;Encrypt=False;TrustServerCertificate=True;Connect Timeout=15;Application Name=DLE-OS Phase2 ReadOnly Regression;');try{$c.Open();$cmd=$c.CreateCommand();$cmd.CommandText=$Query;$a=New-Object Data.SqlClient.SqlDataAdapter($cmd);$t=New-Object Data.DataTable;$null=$a.Fill($t);@($t.Rows|ForEach-Object{$o=[ordered]@{};foreach($col in $t.Columns){$o[$col.ColumnName]=if($_[$col.ColumnName]-is[DBNull]){$null}else{$_[$col.ColumnName]}};[pscustomobject]$o})}finally{$c.Dispose()}}
function ExactProcess {$exe=Join-Path $release 'DleOs.DevOperationalControlHost.exe';@(Get-CimInstance Win32_Process -ErrorAction SilentlyContinue|Where-Object{$_.ExecutablePath-and[string]::Equals($_.ExecutablePath,$exe,[StringComparison]::OrdinalIgnoreCase)}|ForEach-Object{$o=Invoke-CimMethod -InputObject $_ -MethodName GetOwner -ErrorAction SilentlyContinue;[pscustomobject]@{Pid=[int]$_.ProcessId;Path=$_.ExecutablePath;Owner=if($o.ReturnValue-eq0){$o.Domain+'\'+$o.User}else{$null}}})}

$baseline=Get-Content -LiteralPath (Join-Path $Phase1BaselineRoot 'Regression\post-preservation-health.json') -Raw|ConvertFrom-Json
$frontend=Probe 'http://dle-os-host:5051/shared';$operational=Probe 'http://dle-os-host:5051/api/operations-center/v1/work-orders/0115622/verified-status-history' -DefaultCredentials;$canonical=Probe 'http://127.0.0.1:5052/api/platform/live/v1/readiness' -DefaultCredentials;$guard=Probe 'http://127.0.0.1:5052/api/development/v1/security' -DefaultCredentials;$keycloak=Probe 'https://auth.internal.dlemfg.com/realms/dle-os/.well-known/openid-configuration'
$cb=if($canonical.Passed){$canonical.Body|ConvertFrom-Json}else{$null};$gb=if($guard.Passed){$guard.Body|ConvertFrom-Json}else{$null};$canonicalPassed=$canonical.Passed-and$cb.readinessVerdict-eq'Ready'-and$cb.database-eq'DLE_OS_CANONICAL_LIVE';$guardPassed=$guard.Passed-and$gb.verdict-eq'PASS'-and$gb.select-eq'PERMITTED'-and$gb.insert.result-eq'DENIED'-and$gb.update.result-eq'DENIED'-and$gb.delete.result-eq'DENIED'-and$gb.execute-eq'DENIED'
$services=@('MSSQL$SQLEXPRESS','DleOsKeycloak','sshd','BrAmSvc','WinDefend','mpssvc','DleOsDevelopmentFrontend')|ForEach-Object{Get-Service $_ -ErrorAction Stop|Select-Object Name,Status,StartType};$servicesPassed=@($services|Where-Object{$_.Status-ne'Running'-or$_.StartType-ne'Automatic'}).Count-eq0
$listeners=@(Get-NetTCPConnection -State Listen -ErrorAction Stop|Where-Object{$_.LocalPort -in 22,5051,5052,5054,5041,5042,5043}|Select-Object LocalAddress,LocalPort,OwningProcess);$portsPassed=@(22,5051,5052,5054|Where-Object{$port=$_;@($listeners|Where-Object LocalPort -eq $port).Count-eq0}).Count-eq0
$baselineLive=@($baseline.LiveListeners|ForEach-Object{"$($_.LocalAddress)|$($_.LocalPort)"}|Sort-Object);$live=@($listeners|Where-Object{$_.LocalPort -in 5041,5042,5043});$liveUnchanged=(($baselineLive-join',')-ceq(@($live|ForEach-Object{"$($_.LocalAddress)|$($_.LocalPort)"}|Sort-Object)-join','))
$candidate=Get-ScheduledTask -TaskPath '\' -TaskName 'DLE-OS DEV Operational ControlHost 5054 Candidate';$legacy=Get-ScheduledTask -TaskPath '\DLE-OS\Development\' -TaskName 'Operational ControlHost 5054';$action=@($candidate.Actions)[0];$processes=@(ExactProcess);$tasksPassed=$candidate.Settings.Enabled-and$candidate.State-eq'Running'-and$candidate.Principal.UserId-ieq$runtimeIdentity-and[string]$candidate.Principal.LogonType-eq'Password'-and[string]$candidate.Settings.ExecutionTimeLimit-eq'PT0S'-and[string]$candidate.Settings.MultipleInstances-eq'IgnoreNew'-and[int]$candidate.Settings.RestartCount-eq4-and[string]$candidate.Settings.RestartInterval-eq'PT2M'-and[string]$action.WorkingDirectory-eq$release-and[string]$action.Arguments-match[regex]::Escape($release)-and-not$legacy.Settings.Enabled-and$legacy.State-eq'Disabled'
$manifest=Get-Content -LiteralPath $manifestPath -Raw|ConvertFrom-Json;$mismatch=@($manifest.files|Where-Object{$p=Join-Path $release $_.relativePath;-not(Test-Path -LiteralPath $p)-or(Get-Item -LiteralPath $p).Length-ne[int64]$_.length-or(Get-FileHash -LiteralPath $p -Algorithm SHA256).Hash-ne$_.sha256});$releasePassed=$mismatch.Count-eq0-and@(Get-ChildItem -LiteralPath $release -File -Recurse).Count-eq@($manifest.files).Count
$sql=Sql "SET NOCOUNT ON; SELECT (SELECT COUNT_BIG(*) FROM sys.databases WHERE name LIKE 'DLE[_]OS[_]%[_]DEV[_]RESTORE[_]TEST[_]%') RestoreTestDatabaseCount,(SELECT COUNT_BIG(*) FROM sys.databases WHERE name IN ('DLE_OS_OPERATIONAL_DEV','DLE_OS_SECURITY_DEV') AND state_desc='ONLINE' AND user_access_desc='MULTI_USER') ActiveDevOnlineCount;";$sqlPassed=@($sql).Count-eq1-and[int64]$sql[0].RestoreTestDatabaseCount-eq0-and[int64]$sql[0].ActiveDevOnlineCount-eq2
$sac=[int](Get-ItemProperty 'HKLM:\SYSTEM\CurrentControlSet\Control\CI\Policy').VerifiedAndReputablePolicyState;$secureBoot=try{[bool](Confirm-SecureBootUEFI)}catch{$null};$deviceGuard=Get-CimInstance -Namespace root\Microsoft\Windows\DeviceGuard -ClassName Win32_DeviceGuard|Select-Object VirtualizationBasedSecurityStatus,SecurityServicesConfigured,SecurityServicesRunning,CodeIntegrityPolicyEnforcementStatus,UsermodeCodeIntegrityPolicyEnforcementStatus;$defender=Get-MpComputerStatus|Select-Object AMServiceEnabled,AntivirusEnabled,BehaviorMonitorEnabled,RealTimeProtectionEnabled,IsTamperProtected;$securityPassed=$sac-eq[int]$baseline.SacState-and$secureBoot-eq[bool]$baseline.SecureBoot-and$defender.AMServiceEnabled-and$defender.AntivirusEnabled-and$defender.BehaviorMonitorEnabled-and$defender.RealTimeProtectionEnabled
$sshRule=@(Get-NetFirewallRule -DisplayName 'OpenSSH SSH Server (sshd)' -ErrorAction Stop|Where-Object Enabled -eq'True'|ForEach-Object{[ordered]@{Direction=[string]$_.Direction;Action=[string]$_.Action;RemoteAddress=@(Get-NetFirewallAddressFilter -AssociatedNetFirewallRule $_|Select-Object -ExpandProperty RemoteAddress)}});$sshPassed=@($sshRule|Where-Object{$_.Direction-eq'Inbound'-and$_.Action-eq'Allow'-and(@($_.RemoteAddress)-join',')-eq'192.168.0.0/255.255.255.0'}).Count-eq1
$logFiles=@(Get-ChildItem 'C:\ProgramData\DLE-OS\DevelopmentOperationalControl\DevOnly\Logs' -File -Filter 'dev5054-*.jsonl' -ErrorAction SilentlyContinue);$loggingPassed=$logFiles.Count-gt0-and@($logFiles|Where-Object Name -ne'dev5054-current.jsonl').Count-le14-and(($logFiles|Sort-Object LastWriteTimeUtc -Descending|Select-Object -First 4|ForEach-Object{Get-Content $_.FullName -Tail 80})-join"`n")-match[regex]::Escape($ReleaseId)
$passed=$frontend.Passed-and$operational.Passed-and$canonicalPassed-and$guardPassed-and$keycloak.Passed-and$servicesPassed-and$portsPassed-and$liveUnchanged-and$tasksPassed-and$processes.Count-eq1-and$processes[0].Owner-ieq$runtimeIdentity-and$releasePassed-and$sqlPassed-and$securityPassed-and$sshPassed-and$loggingPassed
$result=[ordered]@{Schema='dle-os.phase2-final-regression.v1';CapturedUtc=[DateTimeOffset]::UtcNow;ReleaseId=$ReleaseId;Frontend5051=$frontend;FrontendTo5054=$operational;Canonical5052=[ordered]@{Probe=$canonical;Parsed=$cb;Passed=$canonicalPassed};CanonicalReadOnlyGuard=[ordered]@{Probe=$guard;Parsed=$gb;Passed=$guardPassed};Keycloak=$keycloak;Services=$services;ServicesPassed=$servicesPassed;Listeners=$listeners;RequiredPortsPassed=$portsPassed;LiveListeners=$live;LiveListenersUnchanged=$liveUnchanged;CandidateTask=[ordered]@{State=[string]$candidate.State;Enabled=[bool]$candidate.Settings.Enabled;Principal=$candidate.Principal.UserId;Action=$action;RestartCount=[int]$candidate.Settings.RestartCount;RestartInterval=[string]$candidate.Settings.RestartInterval;ExecutionTimeLimit=[string]$candidate.Settings.ExecutionTimeLimit;MultipleInstances=[string]$candidate.Settings.MultipleInstances};LegacyTask=[ordered]@{State=[string]$legacy.State;Enabled=[bool]$legacy.Settings.Enabled};Processes=$processes;TaskAndProcessPassed=$tasksPassed-and$processes.Count-eq1;ReleaseIntegrity=[ordered]@{FileCount=@($manifest.files).Count;MismatchCount=$mismatch.Count;Passed=$releasePassed};Sql=$sql;SqlPassed=$sqlPassed;SacState=$sac;SecureBoot=$secureBoot;DeviceGuard=$deviceGuard;Defender=$defender;SecurityUnchanged=$securityPassed;SshFirewall=$sshRule;SshFirewallPassed=$sshPassed;LogFiles=@($logFiles|Select-Object Name,Length,LastWriteTimeUtc);LoggingPassed=$loggingPassed;Passed=$passed}
$path=Join-Path $runRoot 'phase2-final-regression.json';$result|ConvertTo-Json -Depth 30|Set-Content -LiteralPath $path -Encoding UTF8
if(-not$passed){throw "Phase 2 final regression failed: $path"};Write-Output $path
