[CmdletBinding()]
param([string]$EvidenceRoot='C:\DLE-OS\Qualification\DevResilience\Phase2')
Set-StrictMode -Version Latest;$ErrorActionPreference='Stop'
$identity=[Security.Principal.WindowsIdentity]::GetCurrent();$principal=New-Object Security.Principal.WindowsPrincipal($identity);if(-not$principal.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)-or-not[string]::Equals($identity.Name,'DLE-OS-HOST\Miguel',[StringComparison]::OrdinalIgnoreCase)){throw 'Phase 2 rollback requires elevated DLE-OS-HOST\Miguel.'}
$taskPath='\';$taskName='DLE-OS DEV Operational ControlHost 5054 Candidate';$runtimeIdentity='DLE-OS-HOST\DLE-OS-DEV-CONTROL';$oldRelease='C:\DLE-OS\Development\OperationalControlHost5054\Releases\dev5054-20260825T170328Z-4e01176a73ea';$legacyPath='\DLE-OS\Development\';$legacyName='Operational ControlHost 5054';$stamp=[DateTimeOffset]::UtcNow.ToString('yyyyMMddTHHmmssZ');$root=Join-Path $EvidenceRoot ('phase2-rollback-'+$stamp);$null=New-Item -ItemType Directory -Path $root -Force;$result=[ordered]@{Schema='dle-os.phase2-rollback.v1';StartedUtc=[DateTimeOffset]::UtcNow;PasswordCapturedInEvidence=$false;Passed=$false};$credential=$null;$plain=$null;$bstr=[IntPtr]::Zero
function Probe{try{$r=Invoke-WebRequest -UseBasicParsing -UseDefaultCredentials -Uri 'http://dle-os-host:5051/api/operations-center/v1/work-orders/0115622/verified-status-history' -TimeoutSec 20;[bool]([int]$r.StatusCode-eq200)}catch{$false}}
function OldProcess{$exe=Join-Path $oldRelease 'DleOs.DevOperationalControlHost.exe';@(Get-CimInstance Win32_Process -ErrorAction SilentlyContinue|Where-Object{$_.ExecutablePath-and[string]::Equals($_.ExecutablePath,$exe,[StringComparison]::OrdinalIgnoreCase)}|ForEach-Object{$o=Invoke-CimMethod -InputObject $_ -MethodName GetOwner -ErrorAction SilentlyContinue;[pscustomobject]@{Pid=[int]$_.ProcessId;Path=$_.ExecutablePath;Owner=if($o.ReturnValue-eq0){$o.Domain+'\'+$o.User}else{$null}}})}
try{$task=Get-ScheduledTask -TaskPath $taskPath -TaskName $taskName;$legacyXml=Export-ScheduledTask -TaskPath $legacyPath -TaskName $legacyName;$currentAction=@($task.Actions)[0];$credential=Get-Credential -UserName $runtimeIdentity -Message 'Enter the existing DLE-OS-DEV-CONTROL password to restore the previous qualified 5054 release.';if($null-eq$credential-or$credential.UserName-ine$runtimeIdentity){throw 'Credential prompt cancelled or returned an unexpected identity.'};$bstr=[Runtime.InteropServices.Marshal]::SecureStringToBSTR($credential.Password);$plain=[Runtime.InteropServices.Marshal]::PtrToStringBSTR($bstr);Stop-ScheduledTask -TaskPath $taskPath -TaskName $taskName -ErrorAction SilentlyContinue;Start-Sleep -Seconds 2;$task=Get-ScheduledTask -TaskPath $taskPath -TaskName $taskName;$task.Settings.RestartCount=0;$task.Settings.RestartInterval='';$launcher=Join-Path $oldRelease 'Start-DevOperationalControlHost5054.ps1';$arguments='-NoLogo -NoProfile -NonInteractive -ExecutionPolicy Bypass -File "'+$launcher+'"';$action=New-ScheduledTaskAction -Execute ([string]$currentAction.Execute) -Argument $arguments -WorkingDirectory $oldRelease;Set-ScheduledTask -TaskPath $taskPath -TaskName $taskName -Action $action -Settings $task.Settings -User $runtimeIdentity -Password $plain|Out-Null;Start-ScheduledTask -TaskPath $taskPath -TaskName $taskName;$deadline=(Get-Date).AddSeconds(150);do{Start-Sleep -Seconds 2;$processes=@(OldProcess);$health=Probe}until(($processes.Count-eq1-and$processes[0].Owner-ieq$runtimeIdentity-and$health)-or(Get-Date)-ge$deadline);$after=Get-ScheduledTask -TaskPath $taskPath -TaskName $taskName;if($processes.Count-ne1-or$processes[0].Owner-ine$runtimeIdentity-or-not$health-or[string]$after.Actions[0].WorkingDirectory-ne$oldRelease-or[int]$after.Settings.RestartCount-ne0-or(Export-ScheduledTask -TaskPath $legacyPath -TaskName $legacyName)-cne$legacyXml){throw 'Previous qualified 5054 release did not recover exactly.'};$result.Task=[ordered]@{State=[string]$after.State;WorkingDirectory=$after.Actions[0].WorkingDirectory;RestartCount=[int]$after.Settings.RestartCount;RestartInterval=[string]$after.Settings.RestartInterval};$result.Process=$processes[0];$result.FrontendTo5054=$health;$result.LegacyUnchanged=$true;$result.Passed=$true}catch{$result.Error=$_.Exception.Message;throw}finally{if($bstr-ne[IntPtr]::Zero){[Runtime.InteropServices.Marshal]::ZeroFreeBSTR($bstr)};$plain=$null;$credential=$null;$result.CompletedUtc=[DateTimeOffset]::UtcNow;$result|ConvertTo-Json -Depth 15|Set-Content -LiteralPath (Join-Path $root 'phase2-rollback.json') -Encoding UTF8}
$result|ConvertTo-Json -Depth 10
