[CmdletBinding()]
param(
 [Parameter(Mandatory=$true)][string]$Stage,
 [Parameter(Mandatory=$true)][ValidatePattern('^dev5054-[0-9]{8}T[0-9]{6}Z-[0-9a-f]{12}$')][string]$ReleaseId,
 [string]$EvidenceRoot='C:\DLE-OS\Qualification\DevResilience\Phase2'
)

Set-StrictMode -Version Latest
$ErrorActionPreference='Stop'
$identity=[Security.Principal.WindowsIdentity]::GetCurrent();$principal=New-Object Security.Principal.WindowsPrincipal($identity)
if(-not$principal.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)-or-not[string]::Equals($identity.Name,'DLE-OS-HOST\Miguel',[StringComparison]::OrdinalIgnoreCase)){throw 'Phase 2 activation requires elevated DLE-OS-HOST\Miguel.'}
$stamp=[DateTimeOffset]::UtcNow.ToString('yyyyMMddTHHmmssZ');$runRoot=Join-Path $EvidenceRoot ('phase2-activation-'+$stamp);$null=New-Item -ItemType Directory -Path $runRoot -Force;Start-Transcript -LiteralPath (Join-Path $runRoot 'activation-transcript.log') -Force|Out-Null
$candidatePath='\';$candidateName='DLE-OS DEV Operational ControlHost 5054 Candidate';$legacyPath='\DLE-OS\Development\';$legacyName='Operational ControlHost 5054';$runtimeIdentity='DLE-OS-HOST\DLE-OS-DEV-CONTROL'
$governedRoot='C:\DLE-OS\Development\OperationalControlHost5054';$releaseRoot=Join-Path $governedRoot 'Releases';$manifestRoot=Join-Path $governedRoot 'Manifests';$newRelease=Join-Path $releaseRoot $ReleaseId;$newManifest=Join-Path $manifestRoot ($ReleaseId+'.json')
$stagePublish=Join-Path $Stage 'publish';$stageManifest=Join-Path $Stage 'release-manifest.json';$logRoot='C:\ProgramData\DLE-OS\DevelopmentOperationalControl\DevOnly\Logs';$failureRoot='C:\ProgramData\DLE-OS\DevelopmentOperationalControl\DevOnly\FailureEvidence';$toolRoot='C:\ProgramData\DLE-OS\DevelopmentOperationalControl\DevOnly\Tools';$failureToolSource='C:\DLE-OS\Repositories\DLE-OS\Tools\DevelopmentRuntime\Export-DleOsDev5054FailureEvidence.ps1';$failureTool=Join-Path $toolRoot 'Export-DleOsDev5054FailureEvidence.ps1';$watcherName='DLE-OS DEV 5054 Failure Evidence Collector'
$result=[ordered]@{Schema='dle-os.phase2-activation.v1';StartedUtc=[DateTimeOffset]::UtcNow;Identity=$identity.Name;ReleaseId=$ReleaseId;Passed=$false;RollbackInvoked=$false;RollbackPassed=$false}
$watcherCreated=$false;$taskChanged=$false;$eventChannelChanged=$false

function TextHash([string]$Text){$sha=[Security.Cryptography.SHA256]::Create();try{([BitConverter]::ToString($sha.ComputeHash([Text.Encoding]::Unicode.GetBytes($Text)))).Replace('-','')}finally{$sha.Dispose()}}
function Probe([string]$Uri){try{$r=Invoke-WebRequest -UseBasicParsing -UseDefaultCredentials -Uri $Uri -TimeoutSec 15;[ordered]@{Passed=([int]$r.StatusCode-eq200);Status=[int]$r.StatusCode;Body=$r.Content}}catch{[ordered]@{Passed=$false;Error=$_.Exception.Message}}}
function NormalizeTaskXml([string]$Text){[xml]$xml=$Text;$ns=New-Object Xml.XmlNamespaceManager($xml.NameTable);$ns.AddNamespace('t','http://schemas.microsoft.com/windows/2004/02/mit/task');foreach($xpath in '/t:Task/t:Actions/t:Exec/t:Arguments','/t:Task/t:Actions/t:Exec/t:WorkingDirectory'){foreach($node in @($xml.SelectNodes($xpath,$ns))){$node.InnerText='<PHASE2_RELEASE_ACTION>'}};$restart=$xml.SelectSingleNode('/t:Task/t:Settings/t:RestartOnFailure',$ns);if($restart){$null=$restart.ParentNode.RemoveChild($restart)};$xml.OuterXml}
function Set-ExactDirectoryAcl([string]$Path,[string]$RuntimeRights){$null=New-Item -ItemType Directory -Path $Path -Force;$acl=Get-Acl $Path;$acl.SetAccessRuleProtection($true,$false);foreach($rule in @($acl.Access)){$null=$acl.RemoveAccessRuleAll($rule)};$inherit=[Security.AccessControl.InheritanceFlags]'ContainerInherit,ObjectInherit';$none=[Security.AccessControl.PropagationFlags]::None;$allow=[Security.AccessControl.AccessControlType]::Allow;$acl.AddAccessRule([Security.AccessControl.FileSystemAccessRule]::new('SYSTEM','FullControl',$inherit,$none,$allow));$acl.AddAccessRule([Security.AccessControl.FileSystemAccessRule]::new('BUILTIN\Administrators','FullControl',$inherit,$none,$allow));if($RuntimeRights){$acl.AddAccessRule([Security.AccessControl.FileSystemAccessRule]::new($runtimeIdentity,$RuntimeRights,$inherit,$none,$allow))};Set-Acl $Path $acl}
function Assert-Manifest([string]$Path,$Manifest){$actual=@(Get-ChildItem -LiteralPath $Path -File -Recurse -Force);if($actual.Count-ne@($Manifest.files).Count){throw "Manifest count mismatch: expected $(@($Manifest.files).Count), actual $($actual.Count)."};foreach($entry in $Manifest.files){$file=[IO.Path]::GetFullPath((Join-Path $Path $entry.relativePath));if(-not$file.StartsWith([IO.Path]::GetFullPath($Path).TrimEnd('\')+'\',[StringComparison]::OrdinalIgnoreCase)-or-not(Test-Path -LiteralPath $file -PathType Leaf)){throw "Manifest path invalid: $($entry.relativePath)"};$item=Get-Item -LiteralPath $file;if($item.Length-ne[int64]$entry.length-or(Get-FileHash -LiteralPath $file -Algorithm SHA256).Hash-ne$entry.sha256){throw "Manifest mismatch: $($entry.relativePath)"}}}
function Get-ExactProcess([string]$Release){$exe=Join-Path $Release 'DleOs.DevOperationalControlHost.exe';@(Get-CimInstance Win32_Process -ErrorAction SilentlyContinue|Where-Object{$_.ExecutablePath-and[string]::Equals($_.ExecutablePath,$exe,[StringComparison]::OrdinalIgnoreCase)}|ForEach-Object{$owner=Invoke-CimMethod -InputObject $_ -MethodName GetOwner -ErrorAction SilentlyContinue;[pscustomobject]@{Pid=[int]$_.ProcessId;ParentPid=[int]$_.ParentProcessId;Started=$_.CreationDate;Path=$_.ExecutablePath;Owner=if($owner.ReturnValue-eq0){$owner.Domain+'\'+$owner.User}else{$null}}})}
function Wait-Healthy([string]$Release,[int]$Seconds=120){$deadline=(Get-Date).AddSeconds($Seconds);do{Start-Sleep -Seconds 2;$processes=Get-ExactProcess $Release;$probe=Probe 'http://dle-os-host:5051/api/operations-center/v1/work-orders/0115622/verified-status-history';if($processes.Count-eq1-and$processes[0].Owner-ieq$runtimeIdentity-and$probe.Passed){return [ordered]@{Passed=$true;Process=$processes[0];FrontendTo5054=$probe}}}while((Get-Date)-lt$deadline);[ordered]@{Passed=$false;Processes=$processes;FrontendTo5054=$probe}}

$candidate=Get-ScheduledTask -TaskPath $candidatePath -TaskName $candidateName;$candidateInfo=Get-ScheduledTaskInfo -TaskPath $candidatePath -TaskName $candidateName;$beforeXml=Export-ScheduledTask -TaskPath $candidatePath -TaskName $candidateName;$legacyBefore=Export-ScheduledTask -TaskPath $legacyPath -TaskName $legacyName;$oldAction=@($candidate.Actions)[0];$oldRelease=[string]$oldAction.WorkingDirectory;$oldArguments=[string]$oldAction.Arguments;$oldExecute=[string]$oldAction.Execute;$oldRestartCount=[int]$candidate.Settings.RestartCount;$oldRestartInterval=[string]$candidate.Settings.RestartInterval;$eventChannel=Get-WinEvent -ListLog 'Microsoft-Windows-TaskScheduler/Operational';$eventWasEnabled=[bool]$eventChannel.IsEnabled
try{
 if(-not$candidate.Settings.Enabled-or$candidate.State-ne'Running'-or$candidate.Principal.UserId-inotmatch'DLE-OS-DEV-CONTROL'-or[string]$candidate.Principal.LogonType-ne'Password'-or[string]$candidate.Principal.RunLevel-ne'Limited'-or[string]$candidate.Settings.ExecutionTimeLimit-ne'PT0S'-or[string]$candidate.Settings.MultipleInstances-ne'IgnoreNew'){throw 'Candidate task is not at the qualified Phase 1 baseline.'}
 $legacy=Get-ScheduledTask -TaskPath $legacyPath -TaskName $legacyName;if($legacy.Settings.Enabled-or$legacy.State-ne'Disabled'){throw 'Legacy task is not disabled.'}
 foreach($path in $stagePublish,$stageManifest,$failureToolSource){if(-not(Test-Path -LiteralPath $path)){throw "Required input absent: $path"}}
 $manifest=Get-Content -LiteralPath $stageManifest -Raw|ConvertFrom-Json;if($manifest.releaseId-ne$ReleaseId-or$manifest.operationalDatabase-ne'DLE_OS_OPERATIONAL_DEV'-or$manifest.securityDatabase-ne'DLE_OS_SECURITY_DEV'-or$manifest.canonicalReadEndpoint-ne'http://DLE-OS-HOST:5052'-or$manifest.expectedServiceIdentity-ne$runtimeIdentity){throw 'Staged manifest violates the fixed DEV boundary.'};Assert-Manifest $stagePublish $manifest
 $preflight=[ordered]@{Frontend5051=Probe 'http://dle-os-host:5051/shared';FrontendTo5054=Probe 'http://dle-os-host:5051/api/operations-center/v1/work-orders/0115622/verified-status-history';Canonical5052=Probe 'http://127.0.0.1:5052/api/platform/live/v1/readiness';CanonicalGuard=Probe 'http://127.0.0.1:5052/api/development/v1/security';OldProcess=Get-ExactProcess $oldRelease};$canonicalBody=if($preflight.Canonical5052.Passed){$preflight.Canonical5052.Body|ConvertFrom-Json}else{$null};$guardBody=if($preflight.CanonicalGuard.Passed){$preflight.CanonicalGuard.Body|ConvertFrom-Json}else{$null};if(@($preflight.GetEnumerator()|Where-Object{$_.Value.PSObject.Properties['Passed']-and-not$_.Value.Passed}).Count-ne0-or@($preflight.OldProcess).Count-ne1-or$canonicalBody.readinessVerdict-ne'Ready'-or$canonicalBody.database-ne'DLE_OS_CANONICAL_LIVE'-or$guardBody.verdict-ne'PASS'-or$guardBody.select-ne'PERMITTED'-or$guardBody.insert.result-ne'DENIED'-or$guardBody.update.result-ne'DENIED'-or$guardBody.delete.result-ne'DENIED'-or$guardBody.execute-ne'DENIED'){throw 'Runtime preflight failed.'};$result.Preflight=$preflight
 if((Test-Path -LiteralPath $newRelease)-or(Test-Path -LiteralPath $newManifest)){throw 'The target immutable release or manifest already exists.'}
 $temporary=Join-Path $releaseRoot ('.phase2-install-'+[guid]::NewGuid().ToString('N'));Copy-Item -LiteralPath $stagePublish -Destination $temporary -Recurse;Assert-Manifest $temporary $manifest;Set-ExactDirectoryAcl $temporary 'ReadAndExecute';Rename-Item -LiteralPath $temporary -NewName $ReleaseId;Copy-Item -LiteralPath $stageManifest -Destination $newManifest;Assert-Manifest $newRelease $manifest
 Set-ExactDirectoryAcl $logRoot 'Modify';Set-ExactDirectoryAcl $failureRoot $null;Set-ExactDirectoryAcl $toolRoot $null;Copy-Item -LiteralPath $failureToolSource -Destination $failureTool -Force
 if(-not$eventWasEnabled){& wevtutil.exe sl 'Microsoft-Windows-TaskScheduler/Operational' /e:true;if($LASTEXITCODE-ne0){throw 'Unable to enable the Task Scheduler Operational channel.'};$eventChannelChanged=$true}
 Stop-ScheduledTask -TaskPath $candidatePath -TaskName $candidateName -ErrorAction Stop;Start-Sleep -Seconds 2
 $candidate=Get-ScheduledTask -TaskPath $candidatePath -TaskName $candidateName;$candidate.Settings.RestartCount=4;$candidate.Settings.RestartInterval='PT2M';$newLauncher=Join-Path $newRelease 'Start-DevOperationalControlHost5054.ps1';$newArguments='-NoLogo -NoProfile -NonInteractive -ExecutionPolicy Bypass -File "'+$newLauncher+'"';$newAction=New-ScheduledTaskAction -Execute $oldExecute -Argument $newArguments -WorkingDirectory $newRelease;Set-ScheduledTask -TaskPath $candidatePath -TaskName $candidateName -Action $newAction -Settings $candidate.Settings|Out-Null;$taskChanged=$true
 $afterXml=Export-ScheduledTask -TaskPath $candidatePath -TaskName $candidateName;if((NormalizeTaskXml $beforeXml)-cne(NormalizeTaskXml $afterXml)){throw 'Candidate task changed outside the approved release action and restart policy.'};$after=Get-ScheduledTask -TaskPath $candidatePath -TaskName $candidateName;if([int]$after.Settings.RestartCount-ne4-or[string]$after.Settings.RestartInterval-ne'PT2M'-or[string]$after.Settings.ExecutionTimeLimit-ne'PT0S'-or[string]$after.Settings.MultipleInstances-ne'IgnoreNew'){throw 'Candidate restart settings do not match the approved bounded policy.'};if((Export-ScheduledTask -TaskPath $legacyPath -TaskName $legacyName)-cne$legacyBefore){throw 'Legacy task changed.'}
 Start-ScheduledTask -TaskPath $candidatePath -TaskName $candidateName;$activation=Wait-Healthy $newRelease 150;if(-not$activation.Passed){throw 'New Phase 2 release did not become healthy.'};$result.Activation=$activation
 $deadline=(Get-Date).AddSeconds(30);do{Start-Sleep -Seconds 1;$log=Get-ChildItem -LiteralPath $logRoot -File -Filter 'dev5054-*.jsonl' -ErrorAction SilentlyContinue|Sort-Object LastWriteTimeUtc -Descending|Select-Object -First 1;$logText=if($log){Get-Content -LiteralPath $log.FullName -Raw}else{''}}until(($logText-match[regex]::Escape($ReleaseId)-and$logText-match'ApplicationStarted')-or(Get-Date)-gt$deadline);if($logText-notmatch[regex]::Escape($ReleaseId)-or$logText-notmatch'ApplicationStarted'){throw 'Durable Phase 2 startup logging was not observed.'}
 $subscription="<QueryList><Query Id='0' Path='Microsoft-Windows-TaskScheduler/Operational'><Select Path='Microsoft-Windows-TaskScheduler/Operational'>*[System[(EventID=102 or EventID=201)]] and *[EventData[Data[@Name='TaskName']='\DLE-OS DEV Operational ControlHost 5054 Candidate']]</Select></Query></QueryList>";$escaped=[Security.SecurityElement]::Escape($subscription);$watcherXml=@"
<?xml version="1.0" encoding="UTF-16"?>
<Task version="1.4" xmlns="http://schemas.microsoft.com/windows/2004/02/mit/task"><RegistrationInfo><Description>Read-only evidence capture when the DEV 5054 candidate action completes.</Description></RegistrationInfo><Triggers><EventTrigger><Enabled>true</Enabled><Subscription>$escaped</Subscription><Delay>PT5S</Delay></EventTrigger></Triggers><Principals><Principal id="Author"><UserId>S-1-5-18</UserId><LogonType>ServiceAccount</LogonType><RunLevel>HighestAvailable</RunLevel></Principal></Principals><Settings><MultipleInstancesPolicy>IgnoreNew</MultipleInstancesPolicy><DisallowStartIfOnBatteries>false</DisallowStartIfOnBatteries><StopIfGoingOnBatteries>false</StopIfGoingOnBatteries><AllowHardTerminate>true</AllowHardTerminate><StartWhenAvailable>true</StartWhenAvailable><RunOnlyIfNetworkAvailable>false</RunOnlyIfNetworkAvailable><Enabled>true</Enabled><Hidden>false</Hidden><ExecutionTimeLimit>PT5M</ExecutionTimeLimit><Priority>7</Priority></Settings><Actions Context="Author"><Exec><Command>powershell.exe</Command><Arguments>-NoLogo -NoProfile -NonInteractive -ExecutionPolicy Bypass -File &quot;$failureTool&quot;</Arguments><WorkingDirectory>$toolRoot</WorkingDirectory></Exec></Actions></Task>
"@;Register-ScheduledTask -TaskPath '\' -TaskName $watcherName -Xml $watcherXml -Force|Out-Null;$watcherCreated=$true
 $result.CandidateXmlBeforePath=Join-Path $runRoot 'candidate-before.xml';$beforeXml|Set-Content -LiteralPath $result.CandidateXmlBeforePath -Encoding Unicode;$result.CandidateXmlAfterPath=Join-Path $runRoot 'candidate-after.xml';$afterXml|Set-Content -LiteralPath $result.CandidateXmlAfterPath -Encoding Unicode;$result.Task=[ordered]@{BeforeSha256=TextHash $beforeXml;AfterSha256=TextHash $afterXml;OnlyApprovedFieldsChanged=$true;RestartCount=4;RestartInterval='PT2M';ExecutionTimeLimit='PT0S';MultipleInstances='IgnoreNew';OldRelease=$oldRelease;NewRelease=$newRelease;Principal=$after.Principal.UserId;LogonType=[string]$after.Principal.LogonType};$result.LegacyUnchanged=$true;$result.EventChannelEnabled=$true;$result.FailureWatcherTask=$watcherName;$result.Passed=$true
}catch{
 $result.Error=$_.Exception.Message;$result.RollbackInvoked=$taskChanged
 if($taskChanged){try{Stop-ScheduledTask -TaskPath $candidatePath -TaskName $candidateName -ErrorAction SilentlyContinue;$rollback=Get-ScheduledTask -TaskPath $candidatePath -TaskName $candidateName;$rollback.Settings.RestartCount=$oldRestartCount;$rollback.Settings.RestartInterval=$oldRestartInterval;$rollbackAction=New-ScheduledTaskAction -Execute $oldExecute -Argument $oldArguments -WorkingDirectory $oldRelease;Set-ScheduledTask -TaskPath $candidatePath -TaskName $candidateName -Action $rollbackAction -Settings $rollback.Settings|Out-Null;Start-ScheduledTask -TaskPath $candidatePath -TaskName $candidateName;$rollbackHealth=Wait-Healthy $oldRelease 150;$result.RollbackHealth=$rollbackHealth;$result.RollbackPassed=$rollbackHealth.Passed}catch{$result.RollbackError=$_.Exception.Message}}
 if($watcherCreated){Unregister-ScheduledTask -TaskPath '\' -TaskName $watcherName -Confirm:$false -ErrorAction SilentlyContinue}
 if($eventChannelChanged){& wevtutil.exe sl 'Microsoft-Windows-TaskScheduler/Operational' /e:false|Out-Null}
 throw
}finally{$result.CompletedUtc=[DateTimeOffset]::UtcNow;$result|ConvertTo-Json -Depth 30|Set-Content -LiteralPath (Join-Path $runRoot 'phase2-activation.json') -Encoding UTF8;Stop-Transcript|Out-Null}
$result|ConvertTo-Json -Depth 15
