USE [master];
GO

IF SUSER_ID(N'DLE-OS-HOST\Miguel') IS NULL
    CREATE LOGIN [DLE-OS-HOST\Miguel] FROM WINDOWS;
GO

IF DB_ID(N'DLE_OS_SECURITY_DEV') IS NULL
BEGIN
    CREATE DATABASE [DLE_OS_SECURITY_DEV];
    ALTER DATABASE [DLE_OS_SECURITY_DEV] SET RECOVERY SIMPLE;
END;
GO

USE [DLE_OS_SECURITY_DEV];
GO

IF USER_ID(N'DLE-OS-HOST\Miguel') IS NULL
    CREATE USER [DLE-OS-HOST\Miguel] FOR LOGIN [DLE-OS-HOST\Miguel];
GO

IF IS_ROLEMEMBER(N'db_owner',N'DLE-OS-HOST\Miguel')<>1
    ALTER ROLE db_owner ADD MEMBER [DLE-OS-HOST\Miguel];
GO
