USE [master];
GO

IF NOT EXISTS (SELECT 1 FROM sys.server_principals WHERE name=N'DLE-OS-HOST\DLE-OS-DEV-FRONTEND')
    CREATE LOGIN [DLE-OS-HOST\DLE-OS-DEV-FRONTEND] FROM WINDOWS;
GO

USE [DLE_OS_SECURITY_DEV];
GO

IF NOT EXISTS (SELECT 1 FROM sys.database_principals WHERE name=N'DLE-OS-HOST\DLE-OS-DEV-FRONTEND')
    CREATE USER [DLE-OS-HOST\DLE-OS-DEV-FRONTEND] FOR LOGIN [DLE-OS-HOST\DLE-OS-DEV-FRONTEND];
GO

GRANT SELECT ON OBJECT::security.ExternalIdentity TO [DLE-OS-HOST\DLE-OS-DEV-FRONTEND];
GRANT SELECT ON OBJECT::security.[User] TO [DLE-OS-HOST\DLE-OS-DEV-FRONTEND];
GRANT SELECT ON OBJECT::security.UserRole TO [DLE-OS-HOST\DLE-OS-DEV-FRONTEND];
GRANT SELECT ON OBJECT::security.[Role] TO [DLE-OS-HOST\DLE-OS-DEV-FRONTEND];
GRANT SELECT ON OBJECT::security.RolePermission TO [DLE-OS-HOST\DLE-OS-DEV-FRONTEND];
GRANT SELECT ON OBJECT::security.Permission TO [DLE-OS-HOST\DLE-OS-DEV-FRONTEND];
GRANT SELECT ON OBJECT::hr.EmployeeDirectoryView TO [DLE-OS-HOST\DLE-OS-DEV-FRONTEND];

GRANT EXECUTE ON OBJECT::security.usp_PrepareEmployeeUserProvisioning TO [DLE-OS-HOST\DLE-OS-DEV-FRONTEND];
GRANT EXECUTE ON OBJECT::security.usp_AbortEmployeeUserProvisioning TO [DLE-OS-HOST\DLE-OS-DEV-FRONTEND];
GRANT EXECUTE ON OBJECT::security.usp_ActivateProvisionedUser TO [DLE-OS-HOST\DLE-OS-DEV-FRONTEND];
GRANT EXECUTE ON OBJECT::security.usp_SetUserEnabledState TO [DLE-OS-HOST\DLE-OS-DEV-FRONTEND];
GRANT EXECUTE ON OBJECT::security.usp_RecordUserSecurityAction TO [DLE-OS-HOST\DLE-OS-DEV-FRONTEND];
GRANT EXECUTE ON OBJECT::security.usp_SetUserRoles TO [DLE-OS-HOST\DLE-OS-DEV-FRONTEND];
GRANT EXECUTE ON OBJECT::security.usp_GetEmployeeUserAdministration TO [DLE-OS-HOST\DLE-OS-DEV-FRONTEND];
GO
