<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Tools\SecurityFoundation\DleOs.Security\DleOs.Security.csproj" />
    <ProjectReference Include="..\..\Tools\TrustedIdentity\DleOs.TrustedIdentity\DleOs.TrustedIdentity.csproj" />
  </ItemGroup>
</Project>
