<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <Compile Include="..\..\Tools\DevelopmentRuntime\DleOs.DevelopmentFrontend\OidcAuthentication.cs"
             Link="OidcAuthentication.cs" />
  </ItemGroup>
</Project>
