[CmdletBinding()]
param()
$ErrorActionPreference = 'Stop'
Set-StrictMode -Version Latest
$repo = (Resolve-Path (Join-Path $PSScriptRoot '..\..')).Path
$root = Join-Path $repo 'Tools\DevelopmentRuntime\DleOs.GovernedRefreshControlHost'
$results = [Collections.Generic.List[object]]::new()
function Text([string]$name) { Get-Content -LiteralPath (Join-Path $root $name) -Raw }
function Need([bool]$value,[string]$message) { if(-not $value){throw $message} }
function Check([string]$name,[scriptblock]$rule){try{&$rule;$results.Add([pscustomobject]@{Test=$name;Result='PASS';Detail=''})}catch{$results.Add([pscustomobject]@{Test=$name;Result='FAIL';Detail=$_.Exception.Message})}}
$program=Text 'Program.cs';$config=Text 'ControlHostRuntimeConfiguration.cs';$identity=Text 'TrustedRefreshIdentity.cs'
$authz=Text 'RefreshPermissionAuthorization.cs';$center=Text 'InvoiceHistoryRefreshCenter.cs';$normal=Text 'NormalUserProcess.cs'
$launcher=Text 'Start-GovernedRefreshControlHost.ps1';$project=Text 'DleOs.GovernedRefreshControlHost.csproj'
$qualification=Text 'QualificationExecutionCenter.cs';$failureWorker=Text 'Invoke-InvoiceHistoryFailureQualification.ps1'
$approval=Text 'New-FailurePreservationQualificationApproval.ps1';$fixtures=Text 'qualification-fixtures.json'
$liveStore=Text 'LiveRunApprovalStore.cs';$hostInstance=Text 'HostInstanceIdentity.cs'
$liveQualification=Text 'LiveApprovalQualificationCenter.cs';$liveApproval=Text 'New-OneRunLiveApproval.ps1'
$liveQualificationApproval=Text 'New-OneRunApprovalQualification.ps1'
$manifest=Get-Content -LiteralPath (Join-Path $root 'worker-dependencies.json') -Raw|ConvertFrom-Json
Check 'fixed DEV boundary' { Need $config.Contains('http://dle-os-host:5057') 'prefix';Need $config.Contains('DLE_OS_SECURITY_DEV') 'security DB';Need $config.Contains('DLE-OS-HOST\DLE-OS') 'identity';Need $config.Contains('ApplicationIntent') 'read-only security intent' }
Check 'exact two-route allowlist' { foreach($r in @('/api/platform/refresh/invoice-history/v1/status','/api/platform/refresh/invoice-history/v1/run')){Need $program.Contains($r) "missing $r"};Need (($program|Select-String 'app.Map' -AllMatches).Matches.Count -eq 2) 'unexpected mapped route';foreach($x in @('MapSyncOperations','MapPlatformRefresh','/health')){Need(-not $program.Contains($x)) "broad surface $x"} }
Check 'execution disabled before live approval' { Need $center.Contains('INVOICE_HISTORY_EXECUTION_DISABLED') 'code';Need $center.Contains('approvals.Inspect()') 'approval inspection';Need $launcher.Contains('DISABLED_FOR_STANDALONE_QUALIFICATION') 'launcher default';Need(-not$config.Contains('ExecutionEnabled')) 'environment-only live bypass remains' }
Check 'qualification and live approvals are mutually exclusive' { Need $config.Contains('APPROVED_FAILURE_PRESERVATION_QUALIFICATION') 'qualification mode';Need $config.Contains('APPROVED_ONE_RUN_GATE_QUALIFICATION') 'gate qualification mode';Need $program.Contains('LiveApprovalQualificationEnabled') 'qualification branch';Need $program.Contains(': center.Start(context)') 'live branch';Need $launcher.Contains('pending-live-approval.json') 'live approval boundary';Need $launcher.Contains('mutually exclusive') 'mutual exclusion';Need $launcher.Contains('Remove-Item -LiteralPath $approvalPath') 'startup qualification consumption' }
Check 'qualification fixture is fixed and source-free' { foreach($x in @('3322BC6B0167A6DC3A3BE2281D68F8F36FC99FAB6372CE865986CD3E03E35AA3','86EBA735B54DA76C77BB1307D71E33EC8633EE49A203616018C6CAD5423C347E','"sourceAccess": "NONE"','"canonicalCommitAllowed": false')){Need $fixtures.Contains($x) "fixture $x"};Need(-not $qualification.Contains('ART-03')) 'qualification host references ART-03';Need(-not $qualification.Contains('ART-13')) 'qualification host references ART-13';Need $failureWorker.Contains('-QualificationInduceFailure') 'controlled importer failure absent' }
Check 'one-shot local approval is release bound' { foreach($x in @('DLE-OS-HOST\Miguel','Administrator','releaseId','expiresAtUtc','AddMinutes(5)','pending-approval.json')){Need($approval.Contains($x)-or$launcher.Contains($x)) "approval $x"};Need $launcher.Contains("approvedBy -cne 'DLE-OS-HOST\Miguel'") 'launcher approver binding' }
Check 'qualification dependency mismatch precedes state' { $mismatch=$qualification.IndexOf('VerifyQualificationMismatch()');$state=$qualification.IndexOf('WriteOwnedState(SharedLease');$worker=$qualification.IndexOf('NormalUserProcess.Start');Need($mismatch-ge0-and$state-gt$mismatch-and$worker-gt$state) 'qualification ordering';Need $qualification.Contains('DependencyMismatchBeforeState') 'pre-state assertion' }
Check 'qualification admission and owned cleanup are fail closed' { foreach($x in @('QUALIFICATION_APPROVAL_CONSUMED','ConcurrentAdmissionRejected','ForeignLiveLeaseBlocked','UnreadableStateBlocked','StaleForeignStateBlocked','DeleteOwnedState(SharedLease','DeleteOwnedState(InvoiceLock')){Need $qualification.Contains($x) "admission $x"} }
Check 'qualification automatically stops after one result' { Need $qualification.Contains('lifetime.StopApplication()') 'host stop absent';Need $qualification.Contains('Interlocked.CompareExchange') 'one-shot claim absent';Need $launcher.Contains('$executionMode = ''DISABLED_FOR_STANDALONE_QUALIFICATION''') 'restart disabled default absent' }
Check 'live approval is exact release and host instance bound' { foreach($x in @('INVOICE_HISTORY','releaseId','hostInstanceId','maximumRuns = 1','approvalId','issuer','durableStatusSha256','evidenceSha256','AddMinutes(10)')){Need($liveApproval.Contains($x)-or$liveStore.Contains($x)) "live approval $x"};Need $hostInstance.Contains('Guid.NewGuid') 'host instance id';Need $hostInstance.Contains('StartedAtUtc') 'host start binding' }
Check 'live approval atomically claims once after admission' { Need $center.Contains('WriteLease(new CanonicalChangeLease') 'admission lease';Need $center.Contains('approvals.TryClaim(requestId)') 'claim absent';Need($center.IndexOf('approvals.TryClaim(requestId)')-gt$center.IndexOf('WriteLease(new CanonicalChangeLease')) 'claim precedes admission';Need $liveStore.Contains('File.Move(PendingPath, consumed)') 'atomic move absent';Need $liveStore.Contains('ALREADY_CLAIMED') 'second claim rejection';Need $center.Contains('WORKER_LAUNCH_FAILED') 'launch failure consumption evidence' }
Check 'one-run qualification is source free and exhaustive' { foreach($x in @('SourceAccess = "NONE"','CanonicalCommitAllowed = false','ExpiredRejected','WrongReleaseRejected','WrongHostInstanceRejected','MalformedRejected','RestartInvalidates','LaunchFailureConsumes','SecondClaimRejected','ReturnedToDisabled')){Need $liveQualification.Contains($x) "gate qualification $x"};Need(-not$liveQualification.Contains('ART-03')) 'gate qualification references ART-03';Need(-not$liveQualification.Contains('ART-13')) 'gate qualification references ART-13' }
Check 'live and qualification approval creators fail mutually exclusive' { Need $liveApproval.Contains('pending-approval.json') 'live creator ignores qualification';Need $approval.Contains('pending-live-approval.json') 'failure creator ignores live';Need $liveQualificationApproval.Contains('pending-live-approval.json') 'gate creator ignores live' }
Check 'qualification execution center is activatable by dependency injection' { Need $qualification.Contains('public QualificationExecutionCenter(IHostApplicationLifetime lifetime)') 'qualification execution center constructor is not public' }
Check 'live approval store has an explicit dependency injection factory' { Need $program.Contains('new LiveRunApprovalStore(') 'approval store DI factory missing';Need $program.Contains('GetRequiredService<HostInstanceIdentity>()') 'host instance is not injected into approval store' }
Check 'trusted assertion boundary' { foreach($x in @('DLE-OS-HOST\DLE-OS-DEV-FRONTEND','Es256IdentityAssertionValidator','OperationalAudience','DevelopmentEnvironment','X-DLE-OS-Correlation-ID','DLE_OS_IDENTITY_ASSERTION_REPLAYED')){Need ($identity.Contains($x) -or $program.Contains($x)) "missing $x"} }
Check 'permission fail closed' { foreach($x in @('sync.operations','DLE_OS_SECURITY_UNAVAILABLE','DLE_OS_USER_DISABLED','DLE_OS_AUTHENTICATION_PENDING')){Need $authz.Contains($x) "missing $x"} }
Check 'shared lease and cross workflow exclusion' { foreach($x in @('C:\ProgramData\DLE-OS\SyncOperations\lease.json','FileMode.CreateNew','InvoiceHistory','DailyOperationsSync','CustomerMaster','OpenSalesOrders','LiveSnapshotRefresh')){Need $center.Contains($x) "missing $x"};Need $center.Contains('DLE_OS_SYNC_OPERATIONS_RUN_ID') 'worker lease handoff' }
Check 'non-admin launch' { foreach($x in @('SaferLevelNormalUser','SaferComputeTokenFromLevel','CreateProcessAsUser')){Need $normal.Contains($x) "missing $x"} }
Check 'worker dependency manifest exact' { Need($manifest.schema -ceq 'dle-os.invoice-history-worker-dependencies.v1') 'schema';Need(@($manifest.dependencies).Count -eq 23) 'count';foreach($d in $manifest.dependencies){Need(Test-Path -LiteralPath $d.path) "absent $($d.path)";Need((Get-FileHash -Algorithm SHA256 -LiteralPath $d.path).Hash -ceq $d.sha256) "hash $($d.path)"} }
Check 'launch boundary re-verifies dependencies' { Need $center.Contains('WorkerDependencyManifest.Verify();') 'launch-time verification absent';Need($center.IndexOf('WorkerDependencyManifest.Verify();') -lt $center.IndexOf('WriteLease(new CanonicalChangeLease')) 'verification occurs after lease creation' }
Check 'qualified chain not compiled or copied' { foreach($x in @('Invoke-InvoiceHistoryRefresh.ps1','Import-InvoiceHistoryRefresh.ps1','build_invoice_history_refresh_package.py')){Need(-not $project.Contains($x)) "worker compiled $x"};Need $center.Contains('Start-InvoiceHistoryRefresh.cmd') 'fixed launcher absent' }
Check 'release pinning and startup verification' { foreach($x in @('release-manifest.json','Get-FileHash','dle-os.governed-refresh-control-release.v1')){Need $launcher.Contains($x) "missing $x"};Need(-not $launcher.Contains('current')) 'current pointer present';Need(-not $launcher.Contains('latest')) 'latest pointer present' }
$results|Format-Table -AutoSize|Out-String|Write-Output
$failed=@($results|? Result -eq 'FAIL');[pscustomobject]@{Total=$results.Count;Passed=$results.Count-$failed.Count;Failed=$failed.Count}|ConvertTo-Json
if($failed.Count){exit 1}
