[CmdletBinding()]
param(
 [string]$OutputRoot='C:\ProgramData\DLE-OS\DevelopmentOperationalControl\DevOnly\FailureEvidence',
 [datetime]$SinceUtc=([datetime]::UtcNow.AddMinutes(-15))
)

Set-StrictMode -Version Latest
$ErrorActionPreference='Stop'
$candidatePath='\';$candidateName='DLE-OS DEV Operational ControlHost 5054 Candidate'
$logRoot='C:\ProgramData\DLE-OS\DevelopmentOperationalControl\DevOnly\Logs'
$stamp=[DateTimeOffset]::UtcNow.ToString('yyyyMMddTHHmmssZ');$runRoot=Join-Path $OutputRoot ('failure-'+$stamp);$null=New-Item -ItemType Directory -Path $runRoot -Force
function Probe([string]$Uri){try{$r=Invoke-WebRequest -UseBasicParsing -Uri $Uri -TimeoutSec 10;[ordered]@{Status=[int]$r.StatusCode;Passed=([int]$r.StatusCode-eq200);Body=$r.Content}}catch{[ordered]@{Passed=$false;Error=$_.Exception.Message}}}
function Events([string]$LogName,[int[]]$Ids,[string]$Pattern){try{$f=@{LogName=$LogName;StartTime=$SinceUtc};if($Ids.Count){$f.Id=$Ids};@(Get-WinEvent -FilterHashtable $f -ErrorAction Stop|Where-Object{$_.Message-match$Pattern}|Select-Object -First 250 TimeCreated,RecordId,Id,LevelDisplayName,ProviderName,ProcessId,Message)}catch{@()}}
$task=Get-ScheduledTask -TaskPath $candidatePath -TaskName $candidateName;$info=Get-ScheduledTaskInfo -TaskPath $candidatePath -TaskName $candidateName;$action=@($task.Actions)[0];$releasePath=[string]$action.WorkingDirectory;$releaseId=Split-Path -Leaf $releasePath;$manifestPath=Join-Path 'C:\DLE-OS\Development\OperationalControlHost5054\Manifests' ($releaseId+'.json');$manifest=Get-Content -LiteralPath $manifestPath -Raw|ConvertFrom-Json
$checks=@($manifest.files|ForEach-Object{$path=Join-Path $releasePath $_.relativePath;[pscustomobject]@{RelativePath=$_.relativePath;ExpectedSha256=$_.sha256;ActualSha256=if(Test-Path $path){(Get-FileHash $path -Algorithm SHA256).Hash}else{$null};ExpectedLength=[int64]$_.length;ActualLength=if(Test-Path $path){(Get-Item $path).Length}else{$null}}})
$processes=@();try{$processes=@(Get-CimInstance Win32_Process|Where-Object{$_.ExecutablePath-and$_.ExecutablePath-ieq(Join-Path $releasePath 'DleOs.DevOperationalControlHost.exe')}|ForEach-Object{$owner=Invoke-CimMethod -InputObject $_ -MethodName GetOwner -ErrorAction SilentlyContinue;[pscustomobject]@{Pid=$_.ProcessId;ParentPid=$_.ParentProcessId;Started=$_.CreationDate;Path=$_.ExecutablePath;CommandLine=$_.CommandLine;Owner=if($owner.ReturnValue-eq0){$owner.Domain+'\'+$owner.User}else{$null}}})}catch{}
$logTails=@(Get-ChildItem -LiteralPath $logRoot -File -Filter 'dev5054-*.jsonl' -ErrorAction SilentlyContinue|Sort-Object LastWriteTimeUtc -Descending|Select-Object -First 4|ForEach-Object{[pscustomobject]@{Path=$_.FullName;Length=$_.Length;LastWriteTimeUtc=$_.LastWriteTimeUtc;Tail=@(Get-Content -LiteralPath $_.FullName -Tail 200)}})
$pattern='DleOs\.DevOperationalControlHost|'+[regex]::Escape($releaseId)+'|5054 Candidate|DLE-OS DEV Operational'
$hpLogs=@(Get-WinEvent -ListLog '*HP*' -ErrorAction SilentlyContinue|Where-Object IsEnabled|Select-Object -ExpandProperty LogName)
$result=[ordered]@{Schema='dle-os.dev5054-failure-evidence.v1';CapturedUtc=[DateTimeOffset]::UtcNow;SinceUtc=$SinceUtc;Identity=[Security.Principal.WindowsIdentity]::GetCurrent().Name;Task=[ordered]@{Enabled=[bool]$task.Settings.Enabled;State=[string]$task.State;RestartCount=[int]$task.Settings.RestartCount;RestartInterval=[string]$task.Settings.RestartInterval;LastRunTime=$info.LastRunTime;LastTaskResult=[int64]$info.LastTaskResult;Action=$action};Processes=$processes;Release=[ordered]@{Id=$releaseId;Path=$releasePath;ManifestPath=$manifestPath;ManifestSha256=(Get-FileHash $manifestPath -Algorithm SHA256).Hash;FileCount=@($checks).Count;IntegrityPassed=@($checks|Where-Object{$_.ExpectedSha256-ne$_.ActualSha256-or$_.ExpectedLength-ne$_.ActualLength}).Count-eq0;Files=$checks};Dependencies=[ordered]@{Frontend5051To5054=Probe 'http://dle-os-host:5051/api/operations-center/v1/work-orders/0115622/verified-status-history';Canonical5052=Probe 'http://127.0.0.1:5052/api/platform/live/v1/readiness';CanonicalGuard=Probe 'http://127.0.0.1:5052/api/development/v1/security'};Events=[ordered]@{TaskScheduler=Events 'Microsoft-Windows-TaskScheduler/Operational' @(100,101,102,103,107,110,111,129,200,201,203,322,323,329) $pattern;Application=Events 'Application' @(1000,1001,1026) $pattern;CodeIntegrity=Events 'Microsoft-Windows-CodeIntegrity/Operational' @(3033,3034,3076,3077,3089) $pattern;Defender=Events 'Microsoft-Windows-Windows Defender/Operational' @() $pattern;Hp=@($hpLogs|ForEach-Object{Events $_ @() $pattern})};LogTails=$logTails;ReadOnlyRuntimeInspection=$true;RuntimeOrSecurityStateChanged=$false}
$path=Join-Path $runRoot 'failure-evidence.json';$result|ConvertTo-Json -Depth 30|Set-Content -LiteralPath $path -Encoding UTF8;$path
